### ISSUE TITLE
Muori Windows!!!!

### ISSUE THREAD

**Issue by Umuril** [The-BFG/BudgetManagement#1]
"C:\Program Files\Java\jdk1.8.0_121\bin\javac.exe" -d class -cp "lib/*" -sourcepath src src/BM/BudgetManagement.java 

cd class
java -cp "lib\*;." BM.BudgetManagement
cd ..

**Comment by The-BFG** [comment]
added the two files compile.bat and run.bat for the execution of the program on windows operating system.
